definitions:
  models.SubscriptionInput:
    properties:
      cost:
        minimum: 0
        type: integer
      end_date:
        type: string
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    required:
    - cost
    - service_name
    - start_date
    - user_id
    type: object
  models.UserSub:
    properties:
      cost:
        type: integer
      end_date:
        type: string
      id:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /subscribe:
    post:
      consumes:
      - application/json
      description: Adds a new subscription to the database.
      parameters:
      - description: Subscription data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/models.SubscriptionInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created subscription
          schema:
            $ref: '#/definitions/models.UserSub'
        "400":
          description: Invalid input parameters or UUID format
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add a new subscription
      tags:
      - subscriptions
  /subscribe/{id}:
    delete:
      description: Deletes a subscription by its ID.
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No content
        "400":
          description: Invalid ID format
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Subscription not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a subscription
      tags:
      - subscriptions
    get:
      description: Retrieves a subscription by its ID.
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Subscription details
          schema:
            $ref: '#/definitions/models.UserSub'
        "400":
          description: Invalid ID format
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Subscription not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get subscription by ID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Updates a subscription by its ID. Creates a new one if not found.
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      - description: Subscription data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/models.SubscriptionInput'
      produces:
      - application/json
      responses:
        "200":
          description: Updated subscription
          schema:
            $ref: '#/definitions/models.UserSub'
        "201":
          description: Created subscription
          schema:
            $ref: '#/definitions/models.UserSub'
        "400":
          description: Invalid input parameters or UUID format
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a subscription
      tags:
      - subscriptions
  /subscriptions:
    get:
      description: Retrieves a list of all subscriptions from database
      produces:
      - application/json
      responses:
        "200":
          description: List of subscriptions
          schema:
            items:
              items:
                $ref: '#/definitions/models.UserSub'
              type: array
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all subscriptions
      tags:
      - subscriptions
  /total-cost:
    get:
      consumes:
      - application/json
      description: Calculates the total cost of subscriptions for a given period,
        optionally filtered by user ID and service name.
      parameters:
      - description: User ID (UUID format)
        in: query
        name: user_id
        type: string
      - description: Service name
        in: query
        name: service_name
        type: string
      - description: Start date of the period (YYYY-MM)
        in: query
        name: start
        required: true
        type: string
      - description: End date of the period (YYYY-MM)
        in: query
        name: end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Total cost
          schema:
            additionalProperties:
              format: float64
              type: number
            type: object
        "400":
          description: Invalid input parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Calculate total cost of subscriptions
      tags:
      - subscriptions
swagger: "2.0"
