services:
  backend:
    build: 
      context: ./aggregator-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      postgres:
          condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=qwerty
      - DB_NAME=aggdb
      - PORT=3000
    networks:
      - sub-network
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: aggdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d aggdb"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - sub-network
    restart: unless-stopped

volumes:
  pgdata:
  
networks:
  sub-network:
    driver: bridge